/* 寰宇侧边栏 v7 · 两套主题对象。
 * v4：剧场版 JSON 37 字段原样（custom_css 除外——皮肤 CSS 由扩展自持）。
 * v6：LIVE_CSS 的 SmartTheme 覆写值反填 + Codex 风格 UI 开关。
 * 皮肤名带「寰宇v7」前缀，供 baibaokuHydrateTheme 注入 themes[] 数组。 */
export const HY_THEMES = {
  v4: {
    name: '寰宇v7 · 剧场版',
    custom_css: '',
    blur_strength: 10,
    main_text_color: 'rgba(223, 223, 223, 0.86)',
    italics_text_color: 'rgba(240, 221, 198, 0.78)',
    underline_text_color: 'rgba(240, 221, 198, 0.9)',
    quote_text_color: 'rgba(251, 219, 179, 0.86)',
    blur_tint_color: 'rgba(18, 20, 36, 0.92)',
    chat_tint_color: 'rgba(18, 20, 36, 1)',
    user_mes_blur_tint_color: 'rgba(205, 86, 122, 0.35)',
    bot_mes_blur_tint_color: 'rgba(199, 230, 223, 0.28)',
    shadow_color: 'rgba(0, 0, 0, 0.85)',
    shadow_width: 0,
    border_color: 'rgba(251, 219, 179, 0)',
    font_scale: 1.05,
    fast_ui_mode: true,
    waifuMode: false,
    avatar_style: 2,
    chat_display: 0,
    toastr_position: 'toast-top-center',
    noShadows: false,
    chat_width: 55,
    timer_enabled: true,
    timestamps_enabled: true,
    timestamp_model_icon: true,
    mesIDDisplay_enabled: true,
    hideChatAvatars_enabled: false,
    message_token_count_enabled: true,
    expand_message_actions: false,
    enableZenSliders: false,
    enableLabMode: false,
    hotswap_enabled: true,
    bogus_folders: true,
    zoomed_avatar_magnification: false,
    reduced_motion: false,
    compact_input_area: true,
    show_swipe_num_all_messages: false,
    click_to_edit: false,
  },
  v6: {
    name: '寰宇v7 · Codex',
    custom_css: '',
    blur_strength: 0,
    main_text_color: 'rgba(242, 242, 242, 1)',
    italics_text_color: 'rgba(168, 180, 255, 1)',
    underline_text_color: 'rgba(168, 180, 255, 1)',
    quote_text_color: 'rgba(190, 190, 190, 1)',
    blur_tint_color: 'rgba(24, 24, 24, 0.96)',
    chat_tint_color: 'rgba(24, 24, 24, 0.96)',
    user_mes_blur_tint_color: 'rgba(34, 34, 34, 0.98)',
    bot_mes_blur_tint_color: 'rgba(24, 24, 24, 0.98)',
    shadow_color: 'rgba(0, 0, 0, 0)',
    shadow_width: 0,
    border_color: 'rgba(255, 255, 255, 0.10)',
    font_scale: 1,
    fast_ui_mode: true,
    waifuMode: false,
    avatar_style: 3,
    chat_display: 0,
    toastr_position: 'toast-top-center',
    noShadows: true,
    chat_width: 55,
    timer_enabled: false,
    timestamps_enabled: true,
    timestamp_model_icon: false,
    mesIDDisplay_enabled: false,
    hideChatAvatars_enabled: false,
    message_token_count_enabled: false,
    expand_message_actions: false,
    enableZenSliders: false,
    enableLabMode: false,
    hotswap_enabled: false,
    bogus_folders: true,
    zoomed_avatar_magnification: false,
    reduced_motion: false,
    compact_input_area: false,
    show_swipe_num_all_messages: false,
    click_to_edit: false,
  },
};

// 首次安装保持酒馆原生主题；由用户明确选择后才应用 v4/v6。
export const DEFAULT_SKIN = '';
export const SKINS = ['v4', 'v6'];
